"""
CONTRA incident report generator.

Turns a completed investigation (findings + collected artifacts + JSONL trace)
into an analyst-style markdown report. Every finding is traceable to the exact
tool execution + evidence hash that produced it (judging criterion #5), and the
trust reasoning is shown explicitly (criterion #6 — another practitioner can follow
why each call was believed or distrusted).

    python -m contra.report --case contra/fixtures/case_blackcat
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .agent import LoopState, Hypothesis, JsonlLogger, run_loop
from .planner_offline import OfflinePlanner
from .providers import FixtureProvider


SEVERITY_BY_RULE = {
    "R1": "HIGH", "R2": "CRITICAL", "R3": "HIGH", "R4": "CRITICAL", "R5": "HIGH",
}


def _read_trace(log_path: Path) -> list[dict]:
    if not log_path.exists():
        return []
    return [json.loads(l) for l in log_path.read_text(encoding="utf-8").splitlines() if l.strip()]


def build_report(state: LoopState, trace: list[dict], case: str) -> str:
    corrects = [r for r in trace if r["event"] == "CORRECT"]
    observes = [r for r in trace if r["event"] == "observe"]

    L: list[str] = []
    L.append(f"# Incident Report — {case}")
    L.append("")
    L.append("> Generated by CONTRA (Anti-Forensic Contradiction Engine). Autonomous "
             "triage; every finding is traced to the tool execution that produced it.")
    L.append("")

    # ── Executive summary ────────────────────────────────────────────────
    sev_counts: dict[str, int] = {}
    for f in state.findings:
        sev = SEVERITY_BY_RULE.get(f["rule_id"], "MEDIUM")
        sev_counts[sev] = sev_counts.get(sev, 0) + 1
    verdict = "MALICIOUS ACTIVITY CONFIRMED" if state.findings else "NO EVIL FOUND"
    L.append("## Executive summary")
    L.append("")
    L.append(f"- **Verdict:** {verdict}")
    L.append(f"- **Findings:** {len(state.findings)} "
             f"({', '.join(f'{n}× {s}' for s, n in sorted(sev_counts.items())) or 'none'})")
    L.append(f"- **Artifacts examined:** {len(state.artifacts)}")
    L.append(f"- **Autonomous iterations:** {state.iteration}")
    L.append(f"- **Self-corrections (contradictions caught):** {len(corrects)}")
    L.append("")

    # ── Findings ─────────────────────────────────────────────────────────
    L.append("## Findings")
    for i, f in enumerate(state.findings, 1):
        sev = SEVERITY_BY_RULE.get(f["rule_id"], "MEDIUM")
        L.append("")
        L.append(f"### {i}. [{f['rule_id']} · {sev}] {f['technique']}")
        L.append("")
        L.append(f"{f['summary']}")
        L.append("")
        L.append(f"- **Why believed:** trusted `{f['trusted_source']}` over "
                 f"`{f['distrusted_source']}` — the distrusted source is the cheaper to forge.")
        L.append(f"- **Confidence (trust delta):** {f['confidence']:.2f}")
        L.append(f"- **Analyst pivot taken:** {f['pivot_hint']}")
        refs = f.get("evidence_refs") or []
        if refs:
            L.append(f"- **Provenance:** `{' '.join(str(x) for x in refs)}`")
    L.append("")

    # ── Self-correction narrative (the demo money-shot, in text) ─────────
    L.append("## Self-correction trace")
    L.append("")
    if corrects:
        L.append("The agent did not trust tool output at face value. Each entry below is a "
                 "point where evidence contradicted itself and the agent re-weighted:")
        L.append("")
        for c in corrects:
            L.append(f"- iter {c['iteration']}: **{c['rule']}** {c['technique']} -- "
                     f"believed `{c['trusted']}`, flagged `{c['distrusted']}` as tampered -> "
                     f"pivoted: {c['pivot']}")
    else:
        L.append("No contradictions detected — evidence was internally consistent.")
    L.append("")

    # ── Evidence provenance table (criterion #5) ─────────────────────────
    L.append("## Evidence provenance")
    L.append("")
    L.append("| Artifact | Source tool | Trust | Command | Evidence SHA-256 |")
    L.append("|----------|-------------|-------|---------|------------------|")
    for atype, a in state.artifacts.items():
        sha = (a.get("evidence_sha256") or "")[:16]
        cmd = " ".join(str(x) for x in a.get("raw_cmd", []))
        L.append(f"| {atype} | {a.get('source_tool','')} | {a.get('trust','')} "
                 f"| `{cmd}` | `{sha}…` |")
    L.append("")
    return "\n".join(L)


def main() -> None:
    ap = argparse.ArgumentParser(description="CONTRA incident report generator")
    ap.add_argument("--case", default="contra/fixtures/case_blackcat")
    ap.add_argument("--max-iterations", type=int, default=15)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    case_name = Path(args.case).name
    log_path = Path("logs") / f"report_{case_name}.jsonl"
    provider = FixtureProvider(args.case)
    state = LoopState(image=args.case, max_iterations=args.max_iterations,
                      hypotheses=[Hypothesis(text="host shows execution of an unknown binary",
                                             priority=0.7)])
    run_loop(state, JsonlLogger(log_path), planner=OfflinePlanner(), tool_caller=provider)

    report = build_report(state, _read_trace(log_path), case_name)
    out = Path(args.out) if args.out else Path("reports") / f"{case_name}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")
    try:
        print(report)
    except UnicodeEncodeError:
        print(report.encode("ascii", "replace").decode("ascii"))
    print(f"\n[written] {out}")


if __name__ == "__main__":
    main()
